spring:
  application:
    name: nacos-config-client
  profiles:
    active: dev
  config:
    import: optional:nacos:${spring.application.name}-${spring.profiles.active}.properties?group=DEFAULT_GROUP
  nacos:
    config:
      server-addr: "127.0.0.1:8848"

server:
  port: 0
