/*
 * This source file was generated by the Gradle 'init' task
 */
package com.taogen.springcloud;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.config.server.EnableConfigServer;

@SpringBootApplication
@EnableConfigServer
public class ConfigServerVaultApplication {

    public static void main(String[] args) {
        SpringApplication.run(ConfigServerVaultApplication.class, args);
    }
}
