import com.google.protobuf.gradle.id

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    // Add protobuf plugin
    id("com.google.protobuf") version "0.9.5"
}
object Versions {
    const val lombokVersion = "1.18.38"
    const val slf4jVersion = "2.0.17"
    const val logbackVersion = "1.5.18"
    const val dotenvVersion = "3.2.0"
    const val grpc = "1.76.0"
    const val protobuf = "4.33.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.bundles.testing)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    // Logging
    implementation(libs.bundles.logging)
    // Lombok
    compileOnly(libs.lombok)
    annotationProcessor(libs.lombok)
    testCompileOnly(libs.lombok)
    testAnnotationProcessor(libs.lombok)

    // This dependency is used by the application.
    implementation(libs.guava)
    // grpc
    implementation("io.grpc:grpc-netty:${Versions.grpc}")
    implementation("io.grpc:grpc-protobuf:${Versions.grpc}")
    implementation("io.grpc:grpc-stub:${Versions.grpc}")
    // protobuf
    implementation("com.google.protobuf:protobuf-java:${Versions.protobuf}")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "com.taogen.App"
}

/**
 * Customizing proto source directories
 */
//sourceSets {
//    main {
//        proto {
//            // In addition to the default 'src/main/proto'
//            srcDir("src/main/protobuf")
//        }
//    }
//    test {
//        proto {
//            // In addition to the default 'src/test/proto'
//            srcDir("src/test/protobuf")
//        }
//    }
//}

/**
 * Customizing Protobuf compilation
 */
protobuf {
    // Locate external executables
    // By default the plugin will search for the protoc executable in the system search path. We recommend you to take the advantage of pre-compiled protoc that published on Maven Central.
    protoc {
        artifact = "com.google.protobuf:protoc:${Versions.protobuf}"
    }

    // Locate the codegen plugins
    plugins {
        // Locate a plugin with name 'grpc'.
        id("grpc") {
            artifact = "io.grpc:protoc-gen-grpc-java:${Versions.grpc}"
        }
    }
    // Customize code generation tasks
    generateProtoTasks {
        all().forEach {
            it.builtins {
                java {
                    // Optionally specify options for the builtin java codegen.
                    // This yields "--java_out=example_option1=true,example_option2:/path/to/output"
                }
            }
            it.plugins {
                // Add grpc output without any option.  grpc must have been defined in the protobuf.plugins block.
                // This yields "--grpc_out=/path/to/output" on the protoc commandline.
                id("grpc") {
                    // Use subdirectory 'grpcjava' instead of the default 'grpc'
//                    outputSubDir = "grpcjava"
                }
            }
        }
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
