spring:
  application:
    name: nacos-service-discovery-1
  config:
    import: optional:nacos:my-config?group=DEFAULT_GROUP
  cloud:
    nacos:
      #      config:
      #        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 0
