eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
server:
  # configure the service use a random port number
  port: 0
management:
  endpoints:
    web:
      exposure:
        include: health,info,beans
#spring:
#  cloud:
#    gateway:
#      discover:
#        locator:
#          lower-case-service-id: true
