eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
server:
  # configure the service use a random port number
  port: 0
management:
  endpoints:
    web:
      exposure:
        include: health,info,beans
