spring:
  application:
    name: eureka-auth-with-keycloak
  config:
    import: optional:configserver:http://localhost:8888,optional:file:.env[.properties],optional:file:../.env[.properties]
  profiles:
    active: dev
