spring:
  application:
    name: eureka-server
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    loadbalancer:
      ribbon:
        enable: false
