spring:
  application:
    name: spring-boot-rabbitmq
  config:
    import: optional:file:.env[.properties],optional:file:../.env[.properties]
  rabbitmq:
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    port: ${RABBITMQ_PORT}
