/*
 * This source file was generated by the Gradle 'init' task
 */
package com.taogen.springcloud;

import org.junit.jupiter.api.Test;

class ConfigServerGitApplicationTest {
    @Test
    void appHasAGreeting() {
        ConfigServerGitApplication classUnderTest = new ConfigServerGitApplication();
    }
}
