/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.14.2/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.10.0"
}

rootProject.name = "spring-microservices-in-action"
include("config-client")
include("config-server-filesystem")
include("config-server-git")
include("config-server-vault")
include("eureka-server")
include("eureka-client-1")
include("eureka-client-2")
include("eureka-spring-cloud-load-balancer")
include("eureka-open-feign")
include("eureka-circuit-breaker-resilience4j")
include("eureka-circuit-breaker-resilience4j-2")
include("eureka-spring-cloud-gateway")
