spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          cloneOnStart: true
          timeout: 10
          uri: git@github.com:tg-playground/spring-cloud-config.git
          defaultLabel: main
          ignoreLocalSshSettings: true
          hostKey: ${hostKey}
          hostKeyAlgorithm: ssh-rsa
          private-key: ${privateKey}


server:
  port: 8888
