/*
 * This source file was generated by the Gradle 'init' task
 */
package com.taogen;

import org.junit.jupiter.api.Test;

class SpringKafkaApplicationTest {
    @Test
    void appHasAGreeting() {
        SpringKafkaApplication classUnderTest = new SpringKafkaApplication();
    }
}
